[server]
ip = "0.0.0.0"
port = 9999
waiting_list_size = 1

[client]
ip = "100.81.188.25" # e.g. 132.12.122.1
port = 9999
reconnect_delay = 5

[logger]
typewriter = false
typewriter_delay = 0.02
timestamp_format = "%H:%M"
log_to_file = true
log_file = "~/.local/share/tchat/server.log"

[chat]
max_message_length = 500
history_size = 50

[colors]
join = "green"
leave = "red"
server = "blue"
timestamp = "white"
error = "red"
info = "yellow"
