[server]
ip = "0.0.0.0"
port = 9999
waiting_list_size = 1

[client]
ip = "100.81.188.25" # e.g. 132.12.122.1
port = 9999
reconnect_delay = 5

[logger]
typewriter = false
typewriter_delay = 0.02
timestamp_format = "%H:%M"
log_to_file = true
log_file = "~/.local/share/tchat/server.log"

[chat]
max_message_length = 500
history_size = 50

[colors]
join = "green"
leave = "red"
server = "blue"
timestamp = "white"
error = "red"
info = "yellow"

[messages]
server_restart = "Server restarting in {}s..."
user_joined = "has entered the chat"
user_left = "has left the chat"
username_taken = "Username '{}' is already taken."
server_online = "Server is back online."
broadcast_joined = "joined the chat"
broadcast_left = "left the chat"
help_text = "\n/whooline - who is online\n/status - server status\n/help - list commands\n/quit - disconnect"
online_format = "Online: {}"
nobody_online = "nobody"
connection_closed = "[ Connection closed ]"
welcome_text = """
[BOOT] Initializing client...
[OK]   Connection established
[AUTH] User authenticated: {}

> Welcome to the system

Available commands:
 - /whoonline
 - /status
 - /help
 - /quit

root@server:~$"""

[admin]
usernames = [ "admin" ]
